apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cloud-portal

resources:
  - ../../../../submodules/cloud-portal/config/base

images:
  - name: ghcr.io/datum-cloud/cloud-portal
    newTag: demo

secretGenerator:
  - name: cloud-portal
    envs:
      - ../../../../submodules/cloud-portal/.env

patches:
  - path: deployment-patch.yaml
  - path: http-route-patch.yaml
