apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../submodules/support/config/overlays/demo
patches:
  - path: auth-patch.yaml
    target:
      kind: Deployment
      name: support-apiserver
